"""
Manages file operations, staging, and backups for the coding agent.

The PatchCoordinator ensures that changes generated by the LLM are handled
safely using a sandbox staging area (.tmp/staging) before being committed to 
the project. It also handles automatic backups and path resolution.
"""

import re
import os
import datetime
import shutil
from pathlib import Path
from typing import Any, Optional, List, Dict
from utils.logger_utils import log_to_file

class PatchCoordinator:
    """
    Handles the safety and persistence layer of the coding session.

    Attributes:
        project_root: The absolute path to the project's root.
        auto_commit: Whether to bypass manual confirmation for file writes.
        backup_dir: Directory where timestamped file backups are stored.
        staging_dir: Sandbox directory for temporary file validation.
    """

    def __init__(self, project_root: str, logger_func=None, auto_commit: bool = False):
        """
        Initializes the coordinator and ensures necessary directories exist.

        Args:
            project_root: The filesystem path to the project.
            logger_func: Optional callback for logging events.
            auto_commit: If True, staged changes are promoted automatically.
        """
        self.project_root = Path(project_root)
        self.logger_func = logger_func or log_to_file
        self.auto_commit = auto_commit
        self._saved_files = []
        self._conversation_history = []
        self._last_patch_result = None
        self._last_warnings = []
        self._current_working_file = None
        
        # Initialize backup system
        self.backup_dir = self.project_root / ".backups"
        self.backup_dir.mkdir(exist_ok=True)
        
        # Initialize sandbox staging area
        self.staging_dir = self.project_root / ".tmp" / "staging"
        self.staging_dir.mkdir(parents=True, exist_ok=True)
        self._staged_files = {} # Maps rel_path -> content for memory-cached access
        
        self.logger_func("PatchCoordinator initialized with sandbox staging support.")

    def _resolve_path(self, base_root: Path, base_filename: str, file_extension: str) -> Path:
        """
        Safely resolves a path, preventing traversal attacks and redundant extensions.

        This ensures that even if an LLM provides a malicious or malformed path,
        the resulting file is restricted to the intended root directory.

        Args:
            base_root: The root directory to resolve against.
            base_filename: The requested filename or relative path.
            file_extension: The expected extension (e.g., 'py').

        Returns:
            A resolved, absolute Path object.
        """
        if not base_filename:
            base_filename = "staged_temp"
            
        # 1. Clean the filename: remove directory traversal markers
        clean_name = base_filename.strip().replace("..", "")
        # Remove absolute path markers to force it into the root
        clean_name = re.sub(r'^([a-zA-Z]:)?[/\\]+', '', clean_name)
        
        # 2. Normalize extensions
        ext = file_extension.lstrip('.')
        if not clean_name.endswith(f".{ext}"):
            clean_name = f"{clean_name}.{ext}"
            
        # 3. Join and resolve to absolute path
        final_path = (base_root / clean_name).resolve()
        
        try:
            # Enforce that the resolved path is still under the base_root
            final_path.relative_to(base_root)
        except ValueError:
            # If resolution escaped the root, force it back to the top level
            final_path = base_root / Path(clean_name).name
            
        return final_path

    def get_staged_path(self, base_filename: str, file_extension: str = "py") -> Path:
        """
        Returns the filesystem Path to a file in the staging area.

        Args:
            base_filename: The name of the file.
            file_extension: The file extension.

        Returns:
            The Path within the staging directory.
        """
        return self._resolve_path(self.staging_dir, base_filename, file_extension)

    def stage_code(self, base_filename: str, content: str, file_extension: str = "py") -> str:
        """
        Writes code to the staging area for validation before production commit.

        The staging area acts as a sandbox. Files here can be linted or tested
        without affecting the actual project codebase.

        Args:
            base_filename: The target filename.
            content: The source code to write.
            file_extension: File extension.

        Returns:
            The string path to the staged file.
        """
        # === SANDBOX STAGING ===
        # We resolve the path specifically within the .tmp/staging directory
        staging_path = self._resolve_path(self.staging_dir, base_filename, file_extension)
        rel_path = str(staging_path.relative_to(self.staging_dir))
        
        try:
            staging_path.parent.mkdir(parents=True, exist_ok=True)
            staging_path.write_text(content, encoding="utf-8")
            self._staged_files[rel_path] = content
            self.logger_func(f"Code staged to sandbox: {staging_path}")
            return str(staging_path)
        except Exception as e:
            error_msg = f"Failed to stage code for {rel_path}: {e}"
            self.logger_func(error_msg, "ERROR")
            raise IOError(error_msg) from e

    def commit_staged_code(self, base_filename: str, file_extension: str = "py", **kwargs) -> str:
        """
        Promotes staged code from the sandbox to the project directory.

        Args:
            base_filename: The filename to promote.
            file_extension: The file extension.
            **kwargs: Additional metadata passed to save_code.

        Returns:
            The string path to the committed file in the project.
        """
        # === PROMOTION TO PRODUCTION ===
        staging_path = self._resolve_path(self.staging_dir, base_filename, file_extension)
        rel_path = str(staging_path.relative_to(self.staging_dir))

        if rel_path not in self._staged_files:
            raise ValueError(f"No staged code found for {rel_path}. Staged: {list(self._staged_files.keys())}")
        
        # Retrieve content from cache and remove from staging
        content = self._staged_files.pop(rel_path)
        if staging_path.exists():
            staging_path.unlink()
            
        # Save to the actual project root (includes automatic backup)
        return self.save_code(base_filename, content, file_extension, **kwargs)

    def clear_staging(self):
        """Removes all files from the staging area and clears the memory cache."""
        if self.staging_dir.exists():
            try:
                shutil.rmtree(self.staging_dir)
            except Exception:
                pass 
            self.staging_dir.mkdir(parents=True, exist_ok=True)
        self._staged_files = {}
        self.logger_func("Staging area cleared.")

    def create_backup(self, file_path: str) -> Optional[str]:
        """
        Creates a timestamped backup of a file before it is overwritten.

        Args:
            file_path: The path to the file to back up.

        Returns:
            The path to the created backup file, or None if failed/unnecessary.
        """
        path = Path(file_path)
        if not path.exists():
            return None
        
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        try:
            # Flatten the directory structure into the filename for easy identification
            rel_path = os.path.relpath(path, self.project_root).replace(os.sep, "_")
        except ValueError:
            rel_path = path.name
            
        backup_name = f"{rel_path}_{timestamp}.bak"
        backup_path = self.backup_dir / backup_name
        
        try:
            shutil.copy2(path, backup_path)
            self.logger_func(f"Created backup: {backup_path}")
            return str(backup_path)
        except Exception as e:
            self.logger_func(f"Failed to create backup for {file_path}: {e}", "WARNING")
            return None

    def save_code(self, base_filename: str, content: str, file_extension: str = "py", 
                  description: Optional[str] = None, operation_type: str = "saved", 
                  feature_context: Optional[str] = None, llm_prompt: Optional[str] = None, 
                  llm_diagnostic: Optional[str] = None, llm_response: Optional[str] = None, 
                  intent: Optional[str] = None) -> str:
        """
        Directly writes code to the project directory and creates a backup.

        Args:
            base_filename: Target filename/path.
            content: Source code.
            file_extension: File extension.
            description: Optional human-readable description of the change.
            operation_type: Type of operation (e.g., 'rewrite', 'patch').
            feature_context: Context about what feature this belongs to.
            llm_prompt: The prompt that generated this change.
            llm_diagnostic: Diagnostic info used for the change.
            llm_response: Raw response from the LLM.
            intent: The high-level goal of the change.

        Returns:
            The absolute string path of the written file.
        """
        file_path = self._resolve_path(self.project_root, base_filename, file_extension)
        full_filename = file_path.name

        # Safety: Backup existing file before over-writing
        if file_path.exists():
            self.create_backup(str(file_path))

        description_text = description or f"Code {operation_type} by LLM."
        if feature_context:
            description_text += f" | Context: {feature_context}"
        
        # Track metadata about the save operation for history and debugging
        file_info = {
            "file_path": str(file_path),
            "filename": full_filename,
            "file_extension": file_extension,
            "description": description_text,
            "operation_type": operation_type,
            "content_preview": content[:200] + "..." if len(content) > 200 else content,
            "llm_prompt": llm_prompt,
            "llm_diagnostic": llm_diagnostic,
            "llm_response": llm_response,
            "intent": intent
        }
        self._saved_files.append(file_info)
        self.set_current_working_file(str(file_path)) 

        try:
            file_path.parent.mkdir(parents=True, exist_ok=True) 
            file_path.write_text(content, encoding="utf-8")
            self.logger_func(f"Successfully wrote file: {file_path}")
        except Exception as e:
            error_msg = f"Error writing file {full_filename}: {str(e)}"
            self.logger_func(error_msg, "ERROR")
            raise IOError(error_msg) from e

        return str(file_path)

    def get_current_working_file(self) -> Optional[str]:
        """Returns the relative path of the file currently being edited."""
        return self._current_working_file

    def set_current_working_file(self, file_path: str):
        """
        Sets the focus on a specific file.

        Args:
            file_path: Path to the file.
        """
        if not file_path or file_path.lower() == 'none':
            return
            
        try:
            rel_path = os.path.relpath(file_path, self.project_root)
            self._current_working_file = rel_path
        except ValueError:
            self._current_working_file = file_path
            
        self.logger_func(f"Focus set to: {self._current_working_file}", "FOCUS_UPDATE")

    def get_conversation_history(self) -> List[Dict[str, str]]:
        """Returns the accumulated LLM conversation history."""
        return self._conversation_history

    def get_recent_history(self, limit: int = 5) -> List[Dict[str, str]]:
        """
        Returns a token-efficient 'sliding window' of the conversation history.
        
        By only sending the most recent exchanges, we maintain context without 
        overwhelming the LLM's attention span or wasting tokens. This prevents
        'context dilution' where the model loses focus on the immediate task.
        """
        # TOKEN MISER: Slice the history to get only the 'limit' most recent messages.
        # This keeps the context window lean and prioritizes recent instructions.
        return self._conversation_history[-limit:]

    def add_to_conversation_history(self, role: str, content: str):
        """
        Adds a turn to the conversation history.

        Args:
            role: The role (e.g., 'user', 'llm').
            content: The text content of the message.
        """
        self._conversation_history.append({"role": role, "content": content})

    def get_last_warnings(self) -> List[str]:
        """Returns the last set of recorded warnings."""
        return self._last_warnings

    def get_last_patch_result(self) -> Optional[Dict[str, Any]]:
        """Returns the result of the last attempted patch operation."""
        return self._last_patch_result

    def set_last_patch_result(self, success: bool, message: str, patch_applied: Optional[bool] = None):
        """
        Records the outcome of a patch operation.

        Args:
            success: Whether the operation succeeded.
            message: Detail message or error.
            patch_applied: Specifically if a patch was applied to the file.
        """
        self._last_patch_result = {"success": success, "message": message, "patch_applied": patch_applied}
