"""
Utilities for extracting source code from LLM Markdown responses.

This module provides functions to parse and isolate code blocks from raw
text generated by the LLM. It supports identifying filenames from 
surrounding context or specialized Markdown syntax.
"""

import re
from typing import List, Tuple

def extract_code_blocks(text: str) -> List[str]:
    """
    Parses standard Markdown code blocks from a string.

    Uses a non-greedy regex to capture everything between triple backticks.

    Args:
        text: The raw response text from the LLM.

    Returns:
        A list of extracted code block strings.
    """
    # Updated regex to handle multi-line code blocks more reliably by using DOTALL
    pattern = r"```(?:\w+)?\s*(.*?)```"
    return re.findall(pattern, text, re.DOTALL)

def extract_code_blocks_with_filenames(text: str, preferred_filename: str) -> List[Tuple[str, str]]:
    """
    Parses Markdown code blocks and attempts to associate them with filenames.

    The function looks for several patterns in descending order of specificity:
    1. Specialized blocks: ```python:filename.py
    2. Header hints: '### filename.py' immediately followed by a code block.
    3. Fallback: Uses the provided 'preferred_filename' for all discovered blocks.

    Args:
        text: The raw response text from the LLM.
        preferred_filename: The filename to use if no specific hint is found.

    Returns:
        A list of tuples in the format (filename, code_content).
    """
    # 1. Look for specialized blocks like ```python:file.py
    # Matches: ```lang:path\ncontent```
    specialized_pattern = r"```(?:\w+)?:([^\s\n]+)\s*(.*?)```"
    specialized_matches = re.findall(specialized_pattern, text, re.DOTALL)
    if specialized_matches:
        return specialized_matches

    # 2. Look for headers followed by blocks
    # Matches: ### main.py\n```python\ncontent```
    header_pattern = r"###\s*([^\s\n]+)\s*\n\s*```(?:\w+)?\s*(.*?)```"
    header_matches = re.findall(header_pattern, text, re.DOTALL)
    if header_matches:
        return header_matches

    # Fallback: Extract all blocks and assign the preferred filename
    blocks = extract_code_blocks(text)
    return [(preferred_filename, block) for block in blocks]
