"""
Executes and validates code generated by the LLM.

The ExecutionEngine handles the 'Act' and 'Validate' phases of the development 
lifecycle. It manages the interaction between the LLM client, the staging area 
in PatchCoordinator, and the local system environment (venv, shell).
"""

import os
import asyncio
from pathlib import Path
from rich.console import Console
from rich.panel import Panel
from refactor_engine import build_system_prompt, build_audit_prompt, get_diagnostic_prompt, get_rewrite_prompt
from validator_engine import verify_code
from code_extractor import extract_code_blocks, extract_code_blocks_with_filenames
from logger_utils import log_to_file

# Initialize Rich console for status updates and error reporting
console = Console(record=True)

class ExecutionEngine:
    """
    Orchestrates coding tasks, bug fixes, and application execution.

    Attributes:
        client: The LLM client instance.
        model: The name of the model to use for generation.
        coordinator: The PatchCoordinator for file operations.
        context_engine: The ContextEngine for gathering project data.
        context_data: Centralized project context for LLM.
    """

    def __init__(self, client, model, coordinator, context_engine, context_data):
        """
        Initializes the execution engine.

        Args:
            client: The LLM backend client.
            model: The specific model to use.
            coordinator: Component for managing file staging/committing.
            context_engine: Component for project mapping and context.
            context_data: Structured project context container.
        """
        self.client = client
        self.model = model
        self.coordinator = coordinator
        self.context_engine = context_engine
        self.context_data = context_data

    def get_python_interpreter(self) -> str:
        """
        Detects if a project-local virtual environment exists.

        It looks for standard '.venv' or 'venv' directories in the project root.
        If found, it returns the path to the python executable within that venv;
        otherwise, it falls back to the system's current python interpreter.

        Returns:
            The string path to the preferred Python executable.
        """
        import sys
        project_dir = self.coordinator.project_root
        # Define common venv locations for Windows (Scripts) and Unix (bin)
        venv_paths = [
            project_dir / ".venv" / "Scripts" / "python.exe" if os.name == 'nt' else project_dir / ".venv" / "bin" / "python",
            project_dir / "venv" / "Scripts" / "python.exe" if os.name == 'nt' else project_dir / "venv" / "bin" / "python",
            project_dir / "env" / "Scripts" / "python.exe" if os.name == 'nt' else project_dir / "env" / "bin" / "python",
        ]
        for p in venv_paths:
            if p.exists(): 
                return str(p)
        return sys.executable

    async def _process_context_requests(self, response_text: str, project_dir: Path) -> Optional[str]:
        """
        Parses the response for [REQUEST_CONTEXT: ...] commands, fulfills them, 
        and returns the retrieved data.
        """
        import re
        match = re.search(r'\[REQUEST_CONTEXT:\s*(.*?)\]', response_text)
        if not match:
            return None
        
        request = match.group(1).strip()
        console.print(f"[bold dim]💡 LLM requested context: {request}[/bold dim]")
        
        # Transparent fulfillment of the request
        if "architecture" in request.lower():
            data = self.context_engine.get_architectural_summary()
        elif "dependencies" in request.lower():
            data = str(self.context_engine.dep_manager.dependency_graph)
        elif "file_contents" in request.lower():
            # Extract filename from: file_contents(filename)
            fname_match = re.search(r'\((.*?)\)', request)
            fname = fname_match.group(1) if fname_match else "main.py"
            try:
                data = (project_dir / fname).read_text(encoding="utf-8")
            except Exception as e:
                data = f"Error retrieving {fname}: {e}"
        else:
            data = "Requested context topic not found."
            
        return f"\n\n--- AUTO-RETRIEVED CONTEXT ({request}) ---\n{data}\n------------------------------------------\n"

    async def run_fix_cycle(self, prompt: str, project_context: str, project_dir: Path):
        """
        Executes a direct full-file rewrite cycle with autonomous context pulling.
        """
        if self.context_data.last_run_error:
            self.coordinator.add_to_conversation_history("system", f"CRITICAL RUNTIME ERROR TO RESOLVE:\n{self.context_data.last_run_error}")
            self.context_data.last_run_error = None

        max_retries = 2
        python_exe = self.get_python_interpreter()
        response_text = ""
        error = None
        
        for attempt in range(max_retries):
            current_target_file = self.coordinator.get_current_working_file() or "main.py"
            
            with console.status(f"[bold yellow]📝 Generating fix (Attempt {attempt+1}/{max_retries})...[/bold yellow]", spinner="bouncingBar"):
                if attempt > 0 and error:
                    rewrite_prompt = f"The previous attempt failed with the following error:\n{error}\n\nPlease analyze your code, address this specific error, and provide the complete, corrected implementation."
                else:
                    rewrite_prompt = get_rewrite_prompt(prompt, "", project_context, target_file=current_target_file)
                
                messages = self.coordinator.get_recent_history(limit=3) + [{"role": "user", "content": rewrite_prompt}]
                response_text = await self.client.chat(self.model, messages)
                
                # Check for autonomous context request
                pulled_context = await self._process_context_requests(response_text, project_dir)
                if pulled_context:
                    # Inject requested context and retry this generation turn
                    self.coordinator.add_to_conversation_history("llm", response_text)
                    self.coordinator.add_to_conversation_history("system", pulled_context)
                    # Loop continues, re-generating the response with new context
                    continue 

                staged_path = self.coordinator.get_staged_path(current_target_file)
                blocks = extract_code_blocks(response_text)
                if blocks:
                    content = blocks[0]
                    self.coordinator.stage_code(current_target_file.replace(".py", ""), content, file_extension="py")
                    success, error, full_report = verify_code(str(staged_path), python_exe=python_exe)
                else:
                    success = False
                    error = "No code blocks found."
                    full_report = "LLM failed to provide a code block."

                console.print(Panel(full_report, title=f"[{'green' if success else 'red'}]Sandbox Report - {'SUCCESS' if success else 'FAILURE'}[/]", border_style="green" if success else "red"))

                if success:
                    self.coordinator.commit_staged_code(current_target_file.replace(".py", ""), file_extension="py")
                    self.coordinator.session_orchestrator.last_run_error = None
                    self.context_engine.scan_project(force=True)
                    break

        self.coordinator.add_to_conversation_history("llm", response_text)
        return response_text

    async def setup_venv(self, project_dir: Path):
        """
        Creates a standard Python virtual environment in the project directory.

        Args:
            project_dir: The directory where the .venv should be created.

        Returns:
            A tuple of (success_bool, error_message).
        """
        import sys
        venv_dir = project_dir / ".venv"
        process = await asyncio.create_subprocess_exec(sys.executable, "-m", "venv", str(venv_dir))
        await process.communicate()
        if process.returncode != 0: 
            return False, "Failed to create venv."
            
        # Ensure the venv is ignored by Git to avoid bloat
        gitignore = project_dir / ".gitignore"
        if not gitignore.exists() or ".venv/" not in gitignore.read_text():
            with open(gitignore, "a") as f: 
                f.write("\n# Project Virtual Environment\n.venv/")
        return True, None

    async def install_dependencies(self, project_dir: Path):
        """
        Installs packages from requirements.txt using the project's venv.

        Args:
            project_dir: The project root directory.

        Returns:
            A tuple of (success_bool, error_message).
        """
        python_exe = self.get_python_interpreter()
        process = await asyncio.create_subprocess_exec(
            python_exe, "-m", "pip", "install", "-r", str(project_dir / "requirements.txt")
        )
        await process.communicate()
        return process.returncode == 0, None

    async def launch_app(self, file_path: str, project_dir: Path):
        """
        Launches the application as a managed subprocess.

        Captures stdout and stderr. If the app crashes, the error is recorded 
        in the orchestrator to inform the next coding cycle.

        Args:
            file_path: The entry point file to run.
            project_dir: The project root.

        Returns:
            A tuple of (success_bool, error_message).
        """
        python_exe = self.get_python_interpreter()
        console.print(f"[bold green]🚀 Launching {file_path} with {python_exe}...[/bold green]")
        
        process = await asyncio.create_subprocess_exec(
            python_exe, file_path,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE
        )
        
        stdout, stderr = await process.communicate()
        
        if process.returncode != 0:
            error_msg = stderr.decode().strip()
            # Feed the runtime error back to the UI/Orchestrator
            self.coordinator.session_orchestrator.last_run_error = error_msg
            log_to_file(f"Runtime Crash: {error_msg}", "RUNTIME_ERROR")
            return False, error_msg
        
        return True, None

    async def run_general_cycle(self, intent: str, prompt: str, project_context: str):
        """
        Orchestrates general code generation or audits.
        Includes a token-efficient sliding window of recent conversation history.
        """
        # Safety: Choose the appropriate system prompt based on the user's intent.
        if intent == "audit":
            system_prompt = build_audit_prompt(intent, project_context)
        else:
            system_prompt = build_system_prompt("python", intent, project_context)
        
        # TOKEN MISER: To ensure clean communication, we provide the LLM with a 
        # short-term memory (last 3 exchanges). This prevents 'amnesia' while 
        # protecting the context window from bloat.
        messages = [{"role": "system", "content": system_prompt}]
        messages.extend(self.coordinator.get_recent_history(limit=3))
        messages.append({"role": "user", "content": prompt})

        with console.status(f"[bold yellow]Generating response using {self.model}...[/bold yellow]", spinner="aesthetic"):
            response_text = await self.client.chat(self.model, messages)
            
            log_to_file(response_text, "REWRITE_RESPONSE")
            self.coordinator.add_to_conversation_history("llm", response_text)
        
        # SAFETY GATE: If the intent is an audit, we STOP here.
        # We explicitly do NOT attempt to extract or commit code to the filesystem.
        if intent == "audit":
            return response_text

        current_target = self.coordinator.get_current_working_file()
        # Handle multiple files if the LLM provides them
        blocks = extract_code_blocks_with_filenames(response_text, preferred_filename=current_target)
        
        for filename, content in blocks:
            # SANITY CHECK: Detect incomplete rewrite (often indicated by very short content)
            if len(content) < 100: 
                console.print(f"[bold yellow]⚠️ Detected incomplete code block for {filename}. Triggering auto-fix...[/bold yellow]")
                fix_prompt = f"The generated code for {filename} appears incomplete. Please provide the COMPLETE, full-file implementation."
                await self.run_fix_cycle(fix_prompt, project_context, self.coordinator.project_root)
                continue

            filename = filename or current_target or "main.py"
            base_filename, file_ext = os.path.splitext(filename)
            # Sandbox first
            self.coordinator.stage_code(base_filename, content, file_extension=file_ext.lstrip('.'))
            
            # Confirm or Auto-Commit
            if self.coordinator.auto_commit or (console.input(f"Commit {filename}? (y/n): ").lower() == 'y'):
                saved_path = self.coordinator.commit_staged_code(base_filename, file_extension=file_ext.lstrip('.'))
                console.print(f"[green]✅ Committed {saved_path}[/green]")
            else:
                self.coordinator.clear_staging()
        
        self.context_engine.scan_project(force=True)
        return response_text
