"""
Executes and validates code generated by the LLM.

The ExecutionEngine handles the 'Act' and 'Validate' phases of the development 
lifecycle. It manages the interaction between the LLM client, the staging area 
in PatchCoordinator, and the local system environment (venv, shell).
"""

import os
import asyncio
from pathlib import Path
from rich.console import Console
from rich.panel import Panel
from llm_tools_and_analysis.llm_prompting_engine import build_system_prompt, build_audit_prompt, get_diagnostic_prompt, get_rewrite_prompt
from llm_tools_and_analysis.validator_engine import verify_code
from llm_tools_and_analysis.code_extractor import extract_code_blocks, extract_code_blocks_with_filenames
from utils.logger_utils import log_to_file

# Initialize Rich console for status updates and error reporting
console = Console(record=True)

class ExecutionEngine:
    """
    Orchestrates coding tasks, bug fixes, and application execution.

    Attributes:
        client: The LLM client instance.
        model: The name of the model to use for generation.
        coordinator: The PatchCoordinator for file operations.
        context_engine: The ContextEngine for gathering project data.
        context_data: Centralized project context for LLM.
    """

    def __init__(self, client, model, coordinator, context_engine, context_data):
        """
        Initializes the execution engine.

        Args:
            client: The LLM backend client.
            model: The specific model to use.
            coordinator: Component for managing file staging/committing.
            context_engine: Component for project mapping and context.
            context_data: Structured project context container.
        """
        self.client = client
        self.model = model
        self.coordinator = coordinator
        self.context_engine = context_engine
        self.context_data = context_data

    def get_python_interpreter(self) -> str:
        """
        Detects if a project-local virtual environment exists.

        It looks for standard '.venv' or 'venv' directories in the project root.
        If found, it returns the path to the python executable within that venv;
        otherwise, it falls back to the system's current python interpreter.

        Returns:
            The string path to the preferred Python executable.
        """
        import sys
        project_dir = self.coordinator.project_root
        # Define common venv locations for Windows (Scripts) and Unix (bin)
        venv_paths = [
            project_dir / ".venv" / "Scripts" / "python.exe" if os.name == 'nt' else project_dir / ".venv" / "bin" / "python",
            project_dir / "venv" / "Scripts" / "python.exe" if os.name == 'nt' else project_dir / "venv" / "bin" / "python",
            project_dir / "env" / "Scripts" / "python.exe" if os.name == 'nt' else project_dir / "env" / "bin" / "python",
        ]
        for p in venv_paths:
            if p.exists(): 
                return str(p)
        return sys.executable

    async def _process_context_requests(self, response_text: str, project_dir: Path) -> Optional[str]:
        """
        Parses the response for [REQUEST_CONTEXT: ...] commands, fulfills them, 
        and returns the retrieved data.
        """
        import re
        match = re.search(r'\[REQUEST_CONTEXT:\s*(.*?)\]', response_text)
        if not match:
            return None
        
        request = match.group(1).strip()
        console.print(f"[bold dim]💡 LLM requested context: {request}[/bold dim]")
        
        # Transparent fulfillment of the request
        if "architecture" in request.lower():
            data = self.context_engine.get_architectural_summary()
        elif "dependencies" in request.lower():
            data = str(self.context_engine.dep_manager.dependency_graph)
        elif "file_contents" in request.lower():
            # Extract filename from: file_contents(filename)
            fname_match = re.search(r'\((.*?)\)', request)
            fname = fname_match.group(1) if fname_match else "main.py"
            try:
                data = (project_dir / fname).read_text(encoding="utf-8")
            except Exception as e:
                data = f"Error retrieving {fname}: {e}"
        else:
            data = "Requested context topic not found."
            
        return f"\n\n--- AUTO-RETRIEVED CONTEXT ({request}) ---\n{data}\n------------------------------------------\n"

    async def run_fix_cycle(self, prompt: str, project_context: str, project_dir: Path):
        """
        Executes a direct full-file rewrite cycle with autonomous context pulling and validation.
        """
        if self.context_data.last_run_error:
            self.coordinator.add_to_conversation_history("system", f"CRITICAL RUNTIME ERROR TO RESOLVE:\n{self.context_data.last_run_error}")
            self.context_data.last_run_error = None

        return await self._generate_with_retry(prompt, project_context, project_dir, is_fix=True)

    async def _generate_with_retry(self, prompt: str, project_context: str, project_dir: Path, is_fix: bool = False, intent: str = "coding"):
        max_retries = 3
        python_exe = self.get_python_interpreter()
        current_target_file = self.coordinator.get_current_working_file() or "main.py"
        
        # Prepare persistent system prompt using the high-level project goal if available
        effective_goal = self.context_data.project_goal if self.context_data.project_goal else intent
        num_modules = len(self.context_data.module_map)
        system_prompt = build_system_prompt("python", effective_goal, project_context, num_modules=num_modules)
        
        attempt = 0
        error = None
        while attempt < max_retries:
            with console.status(f"[bold yellow]📝 Generating {'fix' if is_fix else 'code'} (Attempt {attempt+1}/{max_retries})...[/bold yellow]", spinner="bouncingBar"):
                # === STEP A: PREPARE PROMPT & HISTORY ===
                messages = [{"role": "system", "content": system_prompt}]
                
                # Add context for retries if we previously failed
                if attempt > 0 and error:
                    messages.append({"role": "user", "content": f"Previous attempt failed. Please fix this error: {error}"})
                
                # TOKEN MISER: Include limited recent history to maintain context without bloat.
                # History already contains the user's initial prompt (added in main.py).
                messages.extend(self.coordinator.get_recent_history(limit=5))
                
                # TRANSPARENCY: Show exactly what is being sent to the LLM
                panel_content = []
                for m in messages:
                    role = m['role'].lower()
                    role_color = "cyan" if role == "user" else "magenta" if role == "system" else "green"
                    content_preview = m['content'][:500] + "..." if len(m['content']) > 500 else m['content']
                    panel_content.append(f"[bold {role_color}]{role.upper()}:[/bold {role_color}] {content_preview}")
                
                console.print(Panel(
                    "\n\n".join(panel_content),
                    title=f"[bold blue]MESSAGES SENT TO LLM (Attempt {attempt+1})[/bold blue]",
                    border_style="blue",
                    padding=(1, 2)
                ))

                # === STEP B: LLM GENERATION ===
                response_text = await self.client.chat(self.model, messages)

                # === STEP C: HANDLE AUTONOMOUS CONTEXT REQUESTS ===
                # If the LLM requested more info (e.g., [REQUEST_CONTEXT: ...]), fulfill it and retry immediately
                pulled_context = await self._process_context_requests(response_text, project_dir)
                if pulled_context:
                    self.coordinator.add_to_conversation_history("assistant", response_text)
                    self.coordinator.add_to_conversation_history("system", pulled_context)
                    # Refresh context for the NEXT prompt in THIS attempt
                    project_context, _ = self.context_engine.get_smart_context(prompt, target_file=current_target_file)
                    num_modules = len(self.context_data.module_map)
                    system_prompt = build_system_prompt("python", intent, project_context, num_modules=num_modules)
                    continue 

                # === STEP D: EXTRACT & STAGE CODE BLOCKS ===
                file_blocks = extract_code_blocks_with_filenames(response_text, current_target_file)
                if file_blocks:
                    primary_staged_path = None
                    for filename, content in file_blocks:
                        # Normalize filename and stage to the sandbox (.tmp/staging)
                        base_name = filename.replace(".py", "")
                        staged_path = self.coordinator.stage_code(base_name, content, file_extension="py")
                        
                        # Use the current target or the first file as the primary for verification
                        if not primary_staged_path or filename == current_target_file:
                            primary_staged_path = staged_path
                    
                    # === STEP E: VALIDATION (SYNTAX & RUNTIME) ===
                    # Run the staged code in a subprocess to check for crashes
                    success, error, full_report = verify_code(str(primary_staged_path), python_exe=python_exe)
                else:
                    success = False
                    error = "No code blocks found. Please wrap your code in triple backticks and specify the filename."
                    full_report = "LLM failed to provide a code block."

                console.print(Panel(full_report, title=f"[{'green' if success else 'red'}]Sandbox Report - {'SUCCESS' if success else 'FAILURE'}[/]", border_style="green" if success else "red"))

                # === STEP F: COMMIT OR RETRY ===
                if success:
                    # If validation passed, promote the code from sandbox to production
                    if self.coordinator.auto_commit or (console.input(f"Commit changes to {len(file_blocks)} files? (y/n): ").lower() == 'y'):
                        for filename, _ in file_blocks:
                            self.coordinator.commit_staged_code(filename.replace(".py", ""), file_extension="py")
                        
                        self.context_data.last_run_error = None
                        self.context_engine.scan_project(force=True)
                        self.coordinator.add_to_conversation_history("assistant", response_text)
                        return response_text
                    else:
                        self.coordinator.clear_staging()
                        break
                
                # If validation failed, the error will be fed back to the LLM in the next attempt
                attempt += 1

        self.coordinator.add_to_conversation_history("assistant", response_text)
        return response_text

    async def setup_venv(self, project_dir: Path):
        """
        Creates a standard Python virtual environment in the project directory.

        Args:
            project_dir: The directory where the .venv should be created.

        Returns:
            A tuple of (success_bool, error_message).
        """
        import sys
        venv_dir = project_dir / ".venv"
        process = await asyncio.create_subprocess_exec(sys.executable, "-m", "venv", str(venv_dir))
        await process.communicate()
        if process.returncode != 0: 
            return False, "Failed to create venv."
            
        # Ensure the venv is ignored by Git to avoid bloat
        gitignore = project_dir / ".gitignore"
        if not gitignore.exists() or ".venv/" not in gitignore.read_text():
            with open(gitignore, "a") as f: 
                f.write("\n# Project Virtual Environment\n.venv/")
        return True, None

    async def install_dependencies(self, project_dir: Path):
        """
        Installs packages from requirements.txt using the project's venv.

        Args:
            project_dir: The project root directory.

        Returns:
            A tuple of (success_bool, error_message).
        """
        python_exe = self.get_python_interpreter()
        process = await asyncio.create_subprocess_exec(
            python_exe, "-m", "pip", "install", "-r", str(project_dir / "requirements.txt")
        )
        await process.communicate()
        return process.returncode == 0, None

    async def launch_app(self, file_path: str, project_dir: Path):
        """
        Launches the application in interactive mode.

        By inheriting stdin, stdout, and stderr, the user can interact with 
        CLI apps (like calculators) directly in their terminal.
        """
        python_exe = self.get_python_interpreter()
        console.print(f"[bold green]🚀 Launching {file_path}...[/bold green]")
        console.print("[dim]App is running in interactive mode. Finish the task in the app to return to CLI.[/dim]\n")
        
        try:
            # INTERACTIVE MODE: We do NOT use PIPE here because it blocks input() calls.
            # Instead, we let the subprocess use the parent's terminal streams.
            process = await asyncio.create_subprocess_exec(
                python_exe, file_path,
                stdin=None,
                stdout=None,
                stderr=None,
                cwd=str(project_dir)
            )
            
            await process.wait()
            
            if process.returncode != 0:
                error_msg = f"App exited with non-zero code: {process.returncode}"
                # Even though we didn't capture stderr, the user saw it on their screen.
                self.context_data.last_run_error = error_msg
                log_to_file(error_msg, "RUNTIME_ERROR")
                return False, error_msg
            
            return True, None
        except Exception as e:
            return False, str(e)

    async def run_general_cycle(self, intent: str, prompt: str, project_context: str):
        """
        Orchestrates general code generation or audits.
        """
        # Safety: Choose the appropriate system prompt based on the user's intent.
        if intent == "audit":
            system_prompt = build_audit_prompt(intent, project_context)
            # TOKEN MISER: To ensure clean communication, we provide the LLM with a 
            # short-term memory (last 3 exchanges). This prevents 'amnesia' while 
            # protecting the context window from bloat.
            messages = [{"role": "system", "content": system_prompt}]
            messages.extend(self.coordinator.get_recent_history(limit=3))

            with console.status(f"[bold yellow]Generating response using {self.model}...[/bold yellow]", spinner="aesthetic"):
                response_text = await self.client.chat(self.model, messages)
                
                log_to_file(response_text, "REWRITE_RESPONSE")
                self.coordinator.add_to_conversation_history("assistant", response_text)
                return response_text

        # For coding intent, use the retry logic with validation
        return await self._generate_with_retry(prompt, project_context, self.coordinator.project_root, is_fix=False, intent=intent)
